version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      PGUSER: admin
      PGPASSWORD: adminpass
      PGHOST: postgres
      PGDATABASE: medical_db
      PGPORT: 5432
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: ["npm", "start"]

volumes:
  pgdata:
