version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=postgres
      POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data #persistent database
      - ./db-init:/docker-entrypoint-initdb.d/ #Maps the db-init folder to container folder, so that postgre automatically runs the sql files there at startup
volumes:
  pgdata:
